spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        platform: h2
        # url: jdbc:h2:file:./data/demo
        url: jdbc:h2:mem:demo
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

app:
    CVS_FILE: src/main/resources/data.csv